Fix 'pip' install problem
install 'llvmlite' with pip will cause this error
  error: option --single-version-externally-managed not recognized

this patch fix this problem